ui/deploy/src/generated/defaults.js

Another little tweak to the deployment process.

fix: deploy the defaults.js using on-chain config

---

ui/src/components/vault/VaultManagement/NatPurseAmountInput.jsx

In the Manage Vault page, set a default purse in the forms, and do not zero out the amount inputs when changing purses
Closes https://github.com/Agoric/dapp-token-economy/issues/272

chore: set a default purse and do not zero out amount inputs when changing purses

---

ui/src/components/vault/VaultManagement/AdjustVaultForm.jsx
ui/src/components/vault/VaultManagement/CloseVaultForm.jsx
ui/src/components/vault/VaultManagement/NatPurseAmountInput.jsx
ui/src/components/vault/VaultManagement/VaultManagement.jsx

chore: disable offer button if collateralizationRatio is below liquidationRatio

---

ui/src/components/Swap.jsx
ui/src/components/Treasury.jsx
ui/src/pages/Top.js

- add needed formatting to treasury
- fix the "no vaults" error messages
- NOTE the manage page doesn't require approval because it's top-level

fix: require approval on all screens

---

ui/public/index.html
ui/src/components/vault/VaultManagement/AdjustVaultForm.jsx
ui/src/components/vault/VaultManagement/ChangesTable.jsx
ui/src/components/vault/VaultManagement/CloseVault.jsx
ui/src/components/vault/VaultManagement/CloseVaultForm.jsx
ui/src/components/vault/VaultManagement/CollateralActionChoice.jsx
ui/src/components/vault/VaultManagement/DebtActionChoice.jsx
ui/src/components/vault/VaultManagement/UnchangeableValues.jsx
ui/src/components/vault/VaultManagement/VaultManagement.jsx
ui/src/pages/App.jsx

closes https://github.com/Agoric/dapp-token-economy/issues/237

chore: change manage vault styling

---

ui/public/_redirects

note this has to be pushed to `beta` to go live at https://treasury.agoric.app/
I'd like to look at the deploy preview first...
goal:
fixes: #10

redirect /manageVault etc. to app home page

---

ui/src/components/Swap.jsx

fix: inexact quotes were ignored
fix: apply allowed slippage to the right give/want
fix: increase allowed slippage to 3%

Inexact quotes didn't work

---

README.md
ui/src/components/Treasury.jsx

The current README steps (see below) doesn't include the symlinking step for the CLI tool and just feel lacking compared to the nice write up you guys have at https://agoric.com/documentation/getting-started/before-using-agoric.html
I suggest just linking to that setup guide for the SDK to separate concerns in this README and have the majority of the setup steps be based around this project :) 
```Git clone https://github.com/Agoric/agoric-sdk and pull down the latest from branch master
Navigate to where you cloned agoric-sdk and do yarn install
In agoric-sdk, do yarn build
Git clone this repository, and pull down the latest from branch main
Navigate to where you cloned treasury, and do agoric install```

Update README steps and Treasury component

---

ui/src/components/Swap.jsx
ui/src/components/helpers.js
ui/src/components/vault/VaultConfigure/VaultConfigure.jsx
ui/src/contexts/storeBrandInfo.js
ui/src/types/types.js

This dapp got missed in the conversion to assetKind because there's no CI test for it. 
~~TODO: Kate needs to test locally.~~ Tested this locally both creating a vault and swapping.

chore: update for assetKind

---

exampleDeployScripts/api.js

In preparation for a breaking change to the signature of the helper.

refactor: Relieve dependency on path resolution helper

---

.github/workflows/lint-test.yml
_agstate/agoric-servers/package.json
ui/package.json
yarn.lock

This fixes the eslint modules we use in the ui directory.

chore: update linting

---

ui/jsconfig.json
ui/src/components/vault/VaultManagement/VaultManagement.jsx
ui/src/contexts/Application.jsx
ui/src/contexts/storeBrandInfo.js
ui/src/store.js

Before I realized I should `use-on-chain-config.js`, I was getting `Error: The brand "[undefined]" doesn't look like a brand`. I had trouble figuring out whether `centralBrand` is designed to possibly be `undefined` without type declarations, so I started adding some.
TODO:

docs: declare some latent types

---

package.json

chore: node version updated to >= 14

---

ui/src/components/Swap.jsx
ui/src/components/vault/VaultConfigure/VaultConfigure.jsx
ui/src/components/vault/VaultManagement/AdjustVaultForm.jsx
ui/src/components/vault/VaultManagement/UnchangeableValues.jsx
ui/src/components/vault/VaultManagement/VaultManagement.jsx

ref https://github.com/Agoric/agoric-sdk/issues/4027

fix: fix errors from breaking api changes

---

README.md
exampleDeployScripts/addCollateralType.js
exampleDeployScripts/api.js
ui/src/components/Swap.jsx
ui/src/components/vault/VaultManagement/VaultManagement.jsx
ui/use-on-chain-config.js

See also: https://github.com/Agoric/agoric-sdk/pull/4026
#agoric-sdk-branch: treasWExternalAMM

Update for extracted AMM

---

ui/src/components/vault/NewVault.jsx
ui/src/components/vault/VaultCollateral.jsx
ui/src/components/vault/VaultConfigure/VaultConfigure.jsx
ui/src/components/vault/VaultManagement/VaultManagement.jsx
ui/src/contexts/Application.jsx
ui/src/contexts/storeBrandInfo.js
ui/src/runLoCStub.js
ui/src/store.js
ui/src/types/types.js

author Dan Connolly <dckc@madmode.com> 1635890050 -0500
committer samsiegart <samsiegart@gmail.com> 1638923313 -0800
feat: Start RLoC UI

Initial UI Setup for RUN Line of Credit

---

ui/src/components/Steps.jsx
ui/src/components/Swap.jsx
ui/src/components/Treasury.jsx
ui/src/components/vault/NewVault.jsx
ui/src/components/vault/VaultCollateral.jsx
ui/src/components/vault/VaultSteps.jsx
ui/src/store.js

- Fixes app crash when navigating to swap page before dapp approval/data loaded.
- Shows loading indicators instead of empty states when loading.
- Removes "connect" step since it was being skipped over anyway.

fix: clean up some errors and state wonkiness

---

exampleDeployScripts/contract.js
ui/src/components/vault/NewVault.jsx
ui/src/contexts/Application.jsx
ui/src/generated/defaults.js
ui/use-on-chain-config.js

No attempt to change the name of dapp-treasury or anything visible.
See #4209

keep up with the renaming and relocation of Treasury

---

ui/deploy/src/generated/defaults.js

refs: https://github.com/Agoric/dapp-treasury/issues/61

chore: update deploy defaults for new contract location

---

ui/public/index.html
ui/src/components/NavDrawer.js
ui/src/components/Swap.jsx
ui/src/components/Treasury.jsx
ui/src/components/getRun/GetRun.jsx
ui/src/components/getRun/test/GetRun.test.jsx
ui/src/components/test/NavDrawer.test.jsx
ui/src/components/test/Treasury.test.jsx
ui/src/components/vault/NewVault.jsx
ui/src/components/vault/VaultCollateral.jsx
ui/src/contexts/Application.jsx
ui/src/pages/App.jsx
ui/src/pages/Top.js
ui/src/store.js

refs: #64
Puts a placeholder view in place if the feature flag is enabled:
Also made some layout changes to the app to allow greater flexibility when laying out the view, and added a background gradient to spruce things up.

Scaffolding for getRUN view

---

README.md

refs: https://github.com/Agoric/dapp-treasury/issues/22

Clarify purpose of exampleDeployScripts

---

ui/src/components/Swap.jsx
ui/src/components/Treasury.jsx
ui/src/components/vault/VaultConfigure/CancelButton.jsx
ui/src/components/vault/VaultConfigure/EnterButton.jsx
ui/src/components/vault/VaultCreate.js

fixes: #15
Also fixed compilation error from multiplyBy/divideBy
Before:
After:
Also made some minor layout fix to center the vaults in the treasury view.

fix: add button colors

---

ui/src/components/LoadingBlocks.jsx
ui/src/components/NavDrawer.js
ui/src/components/Treasury.jsx
ui/src/components/VaultSummary.jsx
ui/src/components/WalletConnection.jsx
ui/src/components/test/Treasury.test.jsx
ui/src/components/vault/NewVault.jsx
ui/src/components/vault/VaultManagement/AdjustVaultForm.jsx
ui/src/components/vault/VaultManagement/CloseVaultForm.jsx
ui/src/contexts/Application.jsx
ui/src/pages/Top.js

fixes #45, fixes #78, fixes #79, fixes #80, fixes #81 
Overview of commits:
- Rename "Treasury" view to "Vaults". This is an easy enough fix so I wanted to get it in.
- Fix state/display mismanagement in vaults view. These were all kind of intertwined so I included them all at once (see linked issues for more info). I also made some responsiveness improvements to the vaults view.
- Add animation to vaults pending approval. Just to add some flare, I can take this out of the PR if we decide we don't want it.
(glitch at the start of the animation is fixed)

Display closed vaults properly

---

ui/src/components/vault/VaultCollateral.jsx
ui/src/components/vault/VaultConfigure/CollateralizationPercentInput.jsx
ui/src/components/vault/VaultConfigure/VaultConfigure.jsx
ui/src/types/types.js

fixes https://github.com/Agoric/dapp-treasury/issues/86

fix: remove initialMargin

---

ui/src/components/vault/VaultCollateral.jsx
ui/src/components/vault/VaultConfirmation.jsx
ui/src/components/vault/VaultManagement/test/AdjustVaultForm.test.jsx
ui/src/components/vault/test/VaultCollateral.test.jsx
ui/src/components/vault/test/VaultConfirmation.test.jsx

fixes https://github.com/Agoric/dapp-treasury/issues/90

fix: show interest rate and stability fee correctly

---

ui/src/components/Treasury.jsx
ui/src/contexts/Application.jsx

fixes: https://github.com/Agoric/dapp-treasury/issues/102

fix: handle getPublicNotifiers errors

---

ui/src/components/getRun/EconomyDetails.jsx
ui/src/components/getRun/GetRun.jsx
ui/src/components/getRun/LoadingShimmer.jsx
ui/src/components/getRun/NameValueTable.jsx
ui/src/components/getRun/test/GetRun.test.jsx
ui/src/types/types.js

refs: https://github.com/Agoric/dapp-treasury/issues/71

feat: show runStake governed params

---

ui/src/components/getRun/GetRun.jsx
ui/src/components/getRun/MyBalances.jsx
ui/src/components/getRun/test/GetRun.test.jsx
ui/src/constants.js
ui/src/contexts/Application.jsx
ui/src/store.js
ui/src/types/types.js

fixes: https://github.com/Agoric/dapp-treasury/issues/71

feat: show runStake balances

---

ui/src/components/getRun/Adjust.jsx
ui/src/components/getRun/History.jsx
ui/src/components/getRun/test/History.test.jsx

fixes: https://github.com/Agoric/dapp-treasury/issues/73

feat: close runstake position entirely

---

ui/src/components/vault/VaultManagement/History.jsx
ui/src/components/vault/VaultManagement/VaultManagement.jsx
ui/src/components/vault/VaultManagement/test/History.test.jsx
ui/src/contexts/Application.jsx
ui/src/store.js
ui/src/types/types.js

fixes: https://github.com/Agoric/agoric-sdk/issues/5070

feat: show vault history

---

ui/src/contexts/Application.jsx
ui/src/generated/defaults.js
ui/src/store.js
ui/src/types/types.js
ui/use-on-chain-config.js

refs: https://github.com/Agoric/agoric-sdk/issues/5119

feat: load PSM context

---

ui/src/components/vault/VaultCollateral.jsx
ui/src/contexts/storeBrandInfo.js

Fixes for linting warning that breaks integration build:
https://github.com/Agoric/agoric-sdk/runs/6675271814?check_suite_focus=true

chore: param type casing

---

ui/src/components/Treasury.jsx
ui/src/components/VaultSummary.jsx
ui/src/components/test/Treasury.test.jsx
ui/src/constants.js
ui/src/contexts/Application.jsx

fixes: https://github.com/Agoric/dapp-treasury/issues/83
Did not test e2e, just tested by hardcoding the value at the point where it reads from the notifier. Not sure if there's an easy way to simulate liquidation.

feat: show liquidated vaults

---

ui/src/components/VaultSummary.jsx
ui/src/components/vault/VaultManagement/VaultManagement.jsx
ui/src/types/types.js

refs: https://github.com/Agoric/agoric-sdk/issues/4685

fix: dont depend on removed vault data
